# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e90be36b5802ffae6e06a1e84838a1026c61374836938a467b00cecd42bc9d8dd744bee8661813688b7573c1ca1e3188d574a5a39e75696b0a31404602f4ecde

test:
  secret_key_base: 9f6681776cef57820f72a9fbced9602ca0cf86cfd6d19975edbb9458ff6096be9ee14dd1753063765aac042eca5f7d49d3ae49035c9bfb54ba5fddbc47b10461

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
